- name: trigger
  hosts: localhost
  vars:
    Uname: "admin"
    Pass: "admin"
    HostName: "192.168.1.2:8080"
    TokenName: "11797dbe987f8dfc78f64cf8298666903f"
  tasks:
  - name: Get crumb and session cookie
    uri:
      url: "http://192.168.1.2:8080/crumbIssuer/api/xml?xpath=concat(//crumbRequestField,%22:%22,//crumb)"
      method: GET
      user: "{{ Uname }}"
      password: "{{ Pass }}"
      force_basic_auth: yes
      status_code: 200
      return_content: yes
    register: cookiecrumb
  - name: Queue build
    uri:
      url: "http://{{ HostName }}/job/{{ JobName }}/build?token={{ TokenName }}"
      method: POST
      user: "{{ Uname }}"
      password: "{{ Pass }}"
      force_basic_auth: yes
      status_code: 201
      headers:
        Cookie: "{{ cookiecrumb.cookies_string }}"
        Jenkins-Crumb: "{{ cookiecrumb.content[14:] }}"
